### ISSUE TITLE
Django 1.9 support -- load url from future

### ISSUE THREAD

**Issue by ezegolub** [bread-and-pepper/django-userena#509]
Hi, ``` {% load url from future %} ``` was deprecated in Django 1.9, and it's now failing because of that. Is anyone working on django 1.9 support right now? If not, i can try my hand at it.

**Comment by swistakm** [comment]
There is separate branch for userena 2.0 release that has some django 1.9 support merged. It is still not merged because I had a plan to perform some major code cleanup because it will anyway break backwards compatibility by dropping django 1.4 support. You can try it and maybe propose some improvements.
Any contributions are welcome because I have very little time recently.

-----Wiadomość oryginalna-----
Od: Ezequiel Golub
Wysłano: 2016-01-04 15:15
Do: bread-and-pepper/django-userena
Temat: [django-userena] Django 1.9 support -- load url from future (#509)

Hi, {% load url from future %} was deprecated in Django 19, and it's now failing because of that Is anyone working on django 19 support right now? If not, i can try my hand at it

**Comment by dmk23** [comment]
Why couldn't we just quickly cut a release (e.g. 1.5.2) with full support for 1.9?

Just to have it in the stable branch and not have to deal with major changes ...

**Comment by swistakm** [comment]
Yeah @dmk23 it is a good point and suggestion.

**Comment by swistakm** [comment]
@dmk23 I have looked closer on current work done to support Django 1.9 and noticed that we were forced to drop Django 1.4 support so this needs to be new major release but I think we can at least limit the scope of changes made in 2.0.0 and just postpone major redesign to the 3.0.0 release.

**Comment by swistakm** [comment]
Fixed and released as part of #505
