### ISSUE TITLE
Reset Password Email Validation

### ISSUE THREAD

**Issue by alzearafat** [bread-and-pepper/django-userena#512]
Hi,

I just notice this issue. When I perform reset password but using unregistered email address, it's still pass the validation : 

```
An e-mail has been sent to you which explains how to reset your password
```
When I check my email, of course there's no incoming email regarding password reset, because my email is not registered on the website.

Thank you, Regards

**Comment by swistakm** [comment]
Sorry for late reply. This is a very good question I was wondering many times. Truth is that this is not an issue but exactly the way how it is designed. Actually password reset in userena is almost completely handled by django's built-in `contrib.auth` views. This means that django project is where you should target your question in the fist place. See django documentation that says what happens if you try to reset password of non-existing user: https://docs.djangoproject.com/en/1.9/topics/auth/default/#django.contrib.auth.views.password_reset_done

In my honest opinion this behaviour of Django is simply hilarious and does a lot of harm to the user experience. Some people believe that replying with the same information no matter if email exists makes the site easier. This is supposed to hide information about already registered email addresses from malicious users.

As far as I understand such reasoning the malicious user could at first try to build a base of user emails registered in the site and then perform light attack and take advantage of birthday paradox. In my personal opinion this adds nothing to the security because you will never be able to limit users ability to check if email is already registered. The user will always be able to use registration form in order to check if email is already registered. So tampering with password reset flow is pointless.

If you don't like this exactly like I do, you can simply provide your own template for Django's `password_reset_done` views that changes this message. Unfortunately as far as I know there is no information in that view's template context that would tell you if the email is right so maybe you need to override the PasswordResetForm instead so it won't redirect on invalid emails. So I think this is definitely doable you must consider if it is worth your effort. I don't such default behaviour will never change in userena because I don't wan't to spend rest of my life arguing if it is safe or not to tell if email is valid in this view.

Anyway, if you find a good way to do that then contributions are welcome. Just make it sure that new behaviour is optional and configurable so such change will not surprise old userena users that got used to the default "django's way".

If you're satisfied with my answer then please close this issue.

**Comment by alzearafat** [comment]
Hi @swistakm 

Thank you for the detailed response...  I'm trying to figure it out now :D 

I'll close this issue,
Thank you
